LittlerootTown_NorthApts_2F_Hider::
	faceplayer
	msgbox LittlerootTown_NorthApts_2F_Hider_Text_0
	closemessage
	return


LittlerootTown_NorthApts_2F_Concerned::
	faceplayer
	msgbox LittlerootTown_NorthApts_2F_Concerned_Text_0
	closemessage
	return


LittlerootTown_NorthApts_2F_MapScripts::
	.byte 0

LittlerootTown_NorthApts_2F_Hider_Text_0:
	.string "I buried something special underneath\n"
	.string "one of the small trees on Route 103.\p"
	.string "I'm so sneaky!$"

LittlerootTown_NorthApts_2F_Concerned_Text_0:
	.string "He always buries rare things he finds! I\n"
	.string "just no one will dig them up...$"
