gText_Birch_Welcome::
	.string "Good evening.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "You! I... uh... can barely see you.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "You are about to experience\n"
	.string "something new.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "You will encounter new things.\p"
	.string "You will also recognize many\n"
	.string "friendly faces.$"

gText_Birch_BoyOrGirl::
	.string "Before we begin, please...\p"
	.string "Describe how you look.$"

gText_Birch_WhatsYourName::
	.string "And what's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?\p$"

gText_Birch_YourePlayer::
	.string "Excellent!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "{PLAYER}{KUN}?\n"
	.string "Excellent!\p"
	.string "$"
