gText_Birch_Welcome::
	.string "Gah, it's so dark!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "You! I... uh... can barely see you.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "I can't believe they'd make us\n"
	.string "spend the journey in here.\p"
	.string "Are all the other climbers stuck\n"
	.string "like this too?\p"
	.string "They better not be getting special\n"
	.string "treatment!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Grr...$"

gText_Birch_BoyOrGirl::
	.string "It's so dark!\n"
	.string "Do you look like...\p"
	.string "Or, wait, do you look more like...$"

gText_Birch_WhatsYourName::
	.string "Hey, what's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Nice to meet you!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "We've gotta be getting there soon.\n"
	.string "This sucks!\p"
	.string "$"
