gText_Birch_Welcome::
	.string "Gah, it's so dark!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "You! I... uh... can barely see you.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "I can't believe they'd make us\n"
	.string "spend the journey in here.\p"
	.string "Are all the other climbers stuck\n"
	.string "like this too?\p"
	.string "They better not be getting special\n"
	.string "treatment!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Grr... this sucks.\p"
	.string "I'm gonna give them a piece\n"
	.string "of my mind when we get there!$"

gText_Birch_BoyOrGirl::
	.string "Hey, I can barely see you.\p"
	.string "Describe how you look.$"

gText_Birch_WhatsYourName::
	.string "And what's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Nice to meet you!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "{PLAYER}{KUN}? I'm Emerson.\n"
	.string "Good luck on the climb.\p"
	.string "I'm gonna try and nap for a bit.\n"
	.string "We've gotta be getting there soon.\p"
	.string "$"
