LittlerootTown_PokemonCenter_ChairMan::
	faceplayer
	msgbox LittlerootTown_PokemonCenter_ChairMan_Text_0
	closemessage
	return


LittlerootTown_PokemonCenter_Kid::
	faceplayer
	msgbox LittlerootTown_PokemonCenter_Kid_Text_0
	closemessage
	return


LittlerootTown_PokemonCenter_MapScripts::
	.byte 0

LittlerootTown_PokemonCenter_ChairMan_Text_0:
	.string "There are so few people around now.\p"
	.string "I miss when everyone traveled here from\n"
	.string "across the world.$"

LittlerootTown_PokemonCenter_Kid_Text_0:
	.string "One of the people who was with you\n"
	.string "seems scary. I don't like him at all!$"
