LittlerootTown_WestAptComplex_Man::
	faceplayer
	msgbox LittlerootTown_WestAptComplex_Man_Text_0
	closemessage
	return


LittlerootTown_WestAptComplex_Woman::
	faceplayer
	msgbox LittlerootTown_WestAptComplex_Woman_Text_0
	closemessage
	return


WestAptComplex_MapScripts::
	.byte 0

LittlerootTown_WestAptComplex_Man_Text_0:
	.string "Ah, a climber! I bet you're hoping to go\n"
	.string "all the way to the top. Well, best of\l"
	.string "luck to you. Overcoming the camps is no\l"
	.string "easy feat.$"

LittlerootTown_WestAptComplex_Woman_Text_0:
	.string "Have you noticed all the old men that\n"
	.string "work as camp attendants? Well, they\l"
	.string "aren't really old men. They're mostly\l"
	.string "normal people dressed to look like\l"
	.string "that. It's like a uniform!$"
