LittlerootTown_NorthApts_Boy::
	faceplayer
	msgbox LittlerootTown_NorthApts_Boy_Text_0
	closemessage
	return


LittlerootTown_NorthApts_Woman::
	faceplayer
	msgbox LittlerootTown_NorthApts_Woman_Text_0
	closemessage
	return


LittlerootTown_NorthApts_Woman2::
	faceplayer
	msgbox LittlerootTown_NorthApts_Woman2_Text_0
	closemessage
	return


LittlerootTown_NorthApts_MapScripts::
	.byte 0

LittlerootTown_NorthApts_Boy_Text_0:
	.string "People come from all over to be\n"
	.string "climbers. Some of them are even from\l"
	.string "places I've never heard of!$"

LittlerootTown_NorthApts_Woman_Text_0:
	.string "Everyone knows that any human who\n"
	.string "climbs the mountain gets a wish from\l"
	.string "Jirachi.\p"
	.string "But isn't it interesting that your first\n"
	.string "Pokémon gets one too?$"

LittlerootTown_NorthApts_Woman2_Text_0:
	.string "It's very rare for someone born in the\n"
	.string "Base Camp to move elsewhere.\p"
	.string "Isn't that strange? I suppose that\n"
	.string "living next to a mountain is quite the\l"
	.string "draw.$"
